---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=192.168.1.10 #optional
    volumes:
      - /DISCO_DOCKER/appdata/jellyfin:/config
      - /DATA/media/filmes:/data/movies
    ports:
      - 8096:8096
      #- 8920:8920 #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: unless-stopped