---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
    volumes:
      - /DISCO_DOCKER/appdata/qbittorrent:/config
      - /DATA/media/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped